### ISSUE TITLE
Add an RSS feed

### ISSUE THREAD

**Issue by DLu** [jennschiffer/var-t#4]
Some people still use those and want to keep track of your work.

**Comment by AlgyTaylor** [comment]
:+1: I like a good RSS feed, me

**Comment by jennschiffer** [comment]
rss is not lo-fi enough for this project, but thank you for wanting to keep track and i hope you continue to!

**Comment by brianloveswords** [comment]
Next best thing: follow the RSS feed of the commits to this repo https://github.com/jennschiffer/var-t/commits/gh-pages.atom

**Comment by zachgarwood** [comment]
:+1: for @brianloveswords 's suggestion
